swagger: "2.0"
info:
  version: "0.0.1"
  title: Swagger client
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json 
paths:
  /healthcheck:
    # binds a127 app logic to a route
    x-swagger-router-controller: HealthCheck
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: check
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /word/{word}:
    get:
      summary: Fetches dictionary definitions for a word
      operationId: defs
      x-swagger-router-controller: FetchWord
      parameters:
      - name: word
        in: path
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            type: "array"
            items:
              $ref: "#/definitions/HelloWorldResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - word
    properties:
      word:
        type: string
  
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
